### ISSUE TITLE
Phase 0: Project Plan & Phases Creation

### ISSUE THREAD

**Issue by Yer1k** [Yer1k/Song_Recommender#1]
## Song Recommendation System Project

As we have discussed in our Zoom call, we need to do the following prior to Monday, April 10th, at Midnight

- [x] Find Dataset 

#### Sukhpreet @5ukhy21 
- [x]  #9 
- [x] #3 

#### Dingkun @Yer1k
- [x] #10 
- [x] #1
- [x] #4 
- [x] #5 
- [x] #8 

#### Pragya @pr-124
- [x] #6 
- [x] #7 
- [x] #11 

### Rules of this Repo
1. No direct changes on Main branch

- Instead, create a new branch with an INFORMATIVE branch name; for example, "EDA", "Popularity", etc.
- When you are happy with the branch and want to merge them to Main, please start a PR (Pull Request), and add team members to review

2. In addition to Slack, use Issues for discussion

- If you have found something worth discussing, especially code related, please use issues and tag other team members, so that everyone is on the same page; for instance, @Yer1k @5ukhy21 @pr-124 

3. More to come, and please feel free to comment below any more rules you can come up with. Upon the agreement of everyone, I will add them to this post

**Comment by pr-124** [comment]
#6 Phase 4, #7 Phase 5 and #11 Phase 7 created. All issues for  Phase creation have been raised. Thank you  @5ukhy21 @Yer1k !
