### ISSUE TITLE
Phase 1: Data Cleaning

### ISSUE THREAD

**Issue by 5ukhy21** [Yer1k/Song_Recommender#3]
# Data Cleaning

To ensure our recommendation systems are effective, we need to consider and rectify any data discrepancies within our dataset, which include:

- [x] Checking and handling missing data values (and decide whether to drop NAs or fill where appropriate)
- [x] Use Regex and NLP techniques to delimit data fields and extract for appropriate values
- [x] Ensure data types are correct across dataset
- [x] Transform necessary data columns for data uniformity
- [x] Check for any data duplicates
- [x] Detect any outliers

**Comment by Yer1k** [comment]
Data Cleaning is done, please check [eda.ipynb](https://github.com/Yer1k/Song_Recommender/blob/EDA/eda/eda.ipynb)
No need to worry too much about EDA, let us focus on creating python script of our recommender @5ukhy21 @pr-124
