### ISSUE TITLE
Phase 4: Similarity Recommender based on Artist. 

### ISSUE THREAD

**Issue by pr-124** [Yer1k/Song_Recommender#6]
# Similarity Recommender based on Artist

## Objective:  
Build a music similarity recommender system based on artist names. The system will recommend same and/or similar artists to users based on their input artist.

### Challenges: 

- The dataset contains a list of one or more than one artist names. Searching for a particular artist name within the varying list sizes can be challenging, particularly when dealing with large datasets.

- The dataset may not have enough data on some artists to accurately determine similarities.

### Proposed Solution: 

- Deal with it in pre processing, or use string matching techniques.

- Combine it with the other similarity recommender that uses features, or ask for another input artist.

**Comment by Yer1k** [comment]
Done
