### ISSUE TITLE
Phase 5: Similarity Recommender based on  features of the Song

### ISSUE THREAD

**Issue by pr-124** [Yer1k/Song_Recommender#7]
# Similarity Recommender based on features of the Song

## Objectives:
Build a similarity recommender system that recommends songs based on their features like genre, numerical attributes of the song, and decade it was released. Include features you find compelling.

### Challenges: 

- To include features that would give us a good recommendation system.
- Dealing with inconsistent values in the numerical attributes of the song tracks.
- Combination of varying number of features. 

### Proposed Solution: 
- EDA can help us to gauge which attributes are important.
- Since similar genres sound similar and have more or less similar attributes, including genres can in itself be inclusive of many of these numerical features.

**Comment by Yer1k** [comment]
Fail to incorporate it in main on time

**Comment by Yer1k** [comment]
Test passed
