### ISSUE TITLE
Phase 6: Testing & Merging Code

### ISSUE THREAD

**Issue by Yer1k** [Yer1k/Song_Recommender#8]
# For Testing
We would want to use pytest to cover as much functionality and code as possible and include the documentation about how to run the tests.

1. Tests code creation
- [x] Add a suite of unit tests to repo under tests folder/directory using the pytest framework, for all functions. 

2. Edit the top-level README.md file to include documentation for end users
Include for end users: 
- [x] setup/installation instructions, including information about the expected input file formats
- [x] examples

3.  Edit the top-level README.md file to include documentation for contributors:
- [x] local testing instructions

# For Merging Code

1. Merge different functions into one or two class objects

- Can be based on recommender type or just one class with different recommenders as attributes

2. Code Review

- When we have done with one function or feature, create a PR and assign the other two as code reviewers. After both approvals, we merge the specific branch to Main

**Comment by 5ukhy21** [comment]
We have created, updated, and made test files for parsing data and popularity recommender.
